version: '3.8'

services:
  docker-gs-ping-roach:
    depends-on:
      - roach

    build:
      context: .

    container_name: rest-server
    hostname: rest-server
    networks:
      - mynet

    
    ports:
      - 80:8080
    
    environment:
      - PGUSER=${PGUSER:-totoro}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-26257}
      - PGDATABASE=${PGDATABASE:-mydb}
    deploy:
      restart_policy:
        condition: on-failure


  roach:
    image: cockroachdb/cockroach:latest-v20.1
    ports:
      - 26257:26257
      - 8080:8080
    networks:
      - mynet
    volumes:
      - roach:/cockroach/cockroach-data
    command: start-single-node --insecure

volumes:
  roach:

networks:
  - mynet:
    driver: bridge
